### ISSUE TITLE
Fix build on Java > 8

### ISSUE THREAD

**Issue by kinow** [tupilabs/tap4j#63]
Failing right now on Travis due to `xjc` errors. We may have to drop JMeter integration.

**Comment by kinow** [comment]
```
Exception in thread "main" java.lang.Error: java.lang.reflect.InvocationTargetException
	at com.sun.tools.xjc.reader.Ring.get(Ring.java:113)
	at com.sun.tools.xjc.reader.xmlschema.BGMBuilder.<init>(BGMBuilder.java:147)
	at com.sun.tools.xjc.reader.xmlschema.BGMBuilder.build(BGMBuilder.java:117)
	at com.sun.tools.xjc.ModelLoader.annotateXMLSchema(ModelLoader.java:425)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at com.sun.tools.xjc.Driver.run(Driver.java:333)
	at org.codehaus.mojo.jaxb2.AbstractXjcMojo.execute(AbstractXjcMojo.java:316)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.sun.tools.xjc.reader.Ring.get(Ring.java:102)
	... 29 more
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at com.sun.tools.xjc.reader.Ring.get(Ring.java:113)
	at com.sun.tools.xjc.reader.xmlschema.BindingComponent.getClassSelector(BindingComponent.java:65)
	at com.sun.tools.xjc.reader.xmlschema.ColorBinder.<init>(ColorBinder.java:62)
	at com.sun.tools.xjc.reader.xmlschema.BindGreen.<init>(BindGreen.java:63)
	... 35 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.sun.tools.xjc.reader.Ring.get(Ring.java:102)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: javax/activation/MimeTypeParseException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
	at java.base/java.lang.Class.getConstructor0(Class.java:3343)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2554)
	at com.sun.tools.xjc.reader.Ring.get(Ring.java:100)
	at com.sun.tools.xjc.reader.xmlschema.DefaultClassBinder.<init>(DefaultClassBinder.java:98)
	at com.sun.tools.xjc.reader.xmlschema.ClassSelector.<init>(ClassSelector.java:214)
	... 44 more
Caused by: java.lang.ClassNotFoundException: javax.activation.MimeTypeParseException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 51 more
```

**Comment by kinow** [comment]
After upgrading to 2.5.0 jaxb plugin

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project tap4j: Compilation failure: Compilation failure: 
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/TextEl.java:[11,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/TextEl.java:[12,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/TextEl.java:[13,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/TextEl.java:[14,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/TextEl.java:[15,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/TextEl.java:[35,2] cannot find symbol
[ERROR]   symbol: class XmlAccessorType
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/TextEl.java:[36,2] cannot find symbol
[ERROR]   symbol: class XmlType
[ERROR] /home/kinow/Development/java/workspace/tap4j/src/main/java/org/tap4j/ext/jmeter/parser/JmeterResultParser.java:[20,22] package javax.xml.bind does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/src/main/java/org/tap4j/ext/jmeter/parser/JmeterResultParser.java:[21,22] package javax.xml.bind does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/src/main/java/org/tap4j/ext/jmeter/parser/JmeterResultParser.java:[22,22] package javax.xml.bind does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AbstractSample.java:[13,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AbstractSample.java:[14,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AbstractSample.java:[15,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AbstractSample.java:[16,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AbstractSample.java:[17,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AbstractSample.java:[56,2] cannot find symbol
[ERROR]   symbol: class XmlAccessorType
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AbstractSample.java:[57,2] cannot find symbol
[ERROR]   symbol: class XmlType
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AbstractSample.java:[60,2] cannot find symbol
[ERROR]   symbol: class XmlSeeAlso
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AssertionResult.java:[11,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AssertionResult.java:[12,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/kinow/Development/java/workspace/tap4j/target/generated-sources/jaxb/org/tap4j/ext/jmeter/model/AssertionResult.java:[13,33] package javax.xml.bind.annotation does not exist
```

**Comment by kinow** [comment]
:crossed_fingers:

**Comment by kinow** [comment]
Done

![image](https://user-images.githubusercontent.com/304786/67550457-0806d800-f763-11e9-84a5-715a694086e0.png)
